version: '2'

services:

    database: 
        image: mysql:latest
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
        ports: 
            - "3306:3306"
        container_name: mysql-database            
        hostname: database

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports: 
            - "8080:80"
        depends_on:
            - database
        links: 
            - "database:db"
        container_name: mysql-phpmyadmin
        hostname: phpmyadmin